# Site settings
baseurl = "https://brandykk.gitee.io/"
# languageCode = "en"
languageCode = "zh-cn"
# åç§°
title = "ç™½å°ç”Ÿ"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "your_google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = true

[params]
	author = "ç™½å°ç”Ÿ"
	description = "ä»…ä¸ªäººä½¿ç”¨ç”¨æˆ·è®°å½•å°ä¸œè¥¿æ–¹ä¾¿è‡ªå·±æŸ¥è¯¢è€Œå·²"
	bio = "FUCK EVERYTHING"

	twitter = ""
	facebook = ""

	enableRSS = false
	enableToc = true

	enableDisqus = false
	disqusShortname = ""


	enableSummary = true
	# å¦‚æœåç½®äº‹é¡¹æ›¿æ¢å†…å®¹æ‘˜è¦ä¸­çš„ä½¿ç”¨æè¿°`description`ï¼Œåˆ™å°†è¯¥å€¼è®¾ç½®ä¸ºtrue
	useDescriptionReplaceSummary = true


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = ''

	enableTwitterCard = false
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "ğŸ¡"
	about = "å…³äº"
	archive = "æ—¶é—´çº¿"
	subscribe = "è®¢é˜…"
	tags = "ğŸ“æ ‡ç­¾"

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = false
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	# facebook-square = "https://www.facebook.com/nodejh"
	# twitter-square = "https://www.twitter.com/nodejh"
	github-square = "https://github.com/Virogeny"
	# gitee-square = "https://gitee.com/brandykk"
